#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" <<-EOSQL

CREATE ROLE taskflow_app
WITH LOGIN
PASSWORD '$DATABASE_APP_PASSWORD';

GRANT CONNECT ON DATABASE $POSTGRES_DB TO taskflow_app;
GRANT USAGE ON SCHEMA public TO taskflow_app;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO taskflow_app;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO taskflow_app;

EOSQL